<a href="https://colab.research.google.com/github/choycoy/final_project/blob/main/prediction_bagging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
q_df = pd.read_csv("/content/drive/My Drive/final/questions.csv",sep=",")
q_df['question_id'] = q_df['question_id'].str.replace('q', '')
q_df

,question_id,bundle_id,explanation_id,correct_answer,part,tags,deployed_at
0,1,b1,e1,b,1,1;2;179;181,1558093217098
1,2,b2,e2,a,1,15;2;182,1558093219720
2,3,b3,e3,b,1,14;2;179;183,1558093222784
3,4,b4,e4,b,1,9;2;179;184,1558093225357
4,5,b5,e5,c,1,8;2;179;181,1558093228439
...,...,...,...,...,...,...,...
13164,18139,b12202,e12202,b,2,24;26;183;182,1571733814684
13165,18140,b12203,e12203,a,2,24;33;183;182,1571733815331
13166,18141,b12204,e12204,a,2,24;26;183;182,1571733815951
13167,18142,b12205,e12205,a,2,24;26;183;182,1571733816585
13168,18143,b12206,e12206,c,2,27;24;26;183;182,1571733817400

In [ ]:
df1 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__1.csv",sep=",")
df2 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__2.csv",sep=",")
df3 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__3.csv",sep=",")
df4 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__4.csv",sep=",")
df5 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__5.csv",sep=",")
df6 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__6.csv",sep=",")
df7 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__7.csv",sep=",")
df8 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__8.csv",sep=",")
df9 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__9.csv",sep=",")
df10 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__10.csv",sep=",")
df11 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__11.csv",sep=",")
df12 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__12.csv",sep=",")
df13 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__13.csv",sep=",")
df14 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__14.csv",sep=",")
df15 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__15.csv",sep=",")
df16 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__16.csv",sep=",")
df17 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__17.csv",sep=",")
df18 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__18.csv",sep=",")
df19 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__19.csv",sep=",")
df20 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__20.csv",sep=",")
df21 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__21.csv",sep=",")
df22 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__22.csv",sep=",")
df23 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__23.csv",sep=",")
df24 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__24.csv",sep=",")
df25 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__25.csv",sep=",")
df26 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__26.csv",sep=",")
df27 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__27.csv",sep=",")
df28 = pd.read_csv("/content/drive/My Drive/final/combined_with_filename__28.csv",sep=",")


df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8,df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20,df21, df22,df23, df24, df25, df26, df27, df28])

In [ ]:
df['question_id'] = df['question_id'].astype('int64')
q_df['question_id'] = q_df['question_id'].astype('int64')

# Merge the dataframes on 'question_id'
merged_df = pd.merge(df, q_df[['question_id', 'correct_answer']], on='question_id', how='left')

# Create the 'is_correct' column based on the comparison between 'user_answer' and 'correct_answer'
merged_df['is_correct'] = (merged_df['user_answer'] == merged_df['correct_answer']).astype(int)

# Now merged_df will have a new column 'is_correct' indicating if the user_answer is correct or not
print(merged_df)

              timestamp  solving_id  question_id user_answer  elapsed_time  \
0         1565096190868           1         5012           b         38000
1         1565096221062           2         4706           c         24000
2         1565096293432           3         4366           b         68000
3         1565096339668           4         4829           a         42000
4         1565096401774           5         6528           b         59000
...                 ...         ...          ...         ...           ...
27904652  1574639347000        1263         8599           a         19000
27904653  1574639368000        1264         8972           a         13000
27904654  1574639410000        1265         8812           c         34000
27904655  1574639466000        1266         8690           b         15000
27904656  1574639507000        1267         9558           d         29000

          user_id correct_answer  is_correct
0               1              c           0
1               1              c           1
2               1              b           1
3               1              c           0
4               1              d           0
...           ...            ...         ...
27904652     9999              a           1
27904653     9999              a           1
27904654     9999              c           1
27904655     9999              b           1
27904656     9999              d           1

[27904657 rows x 8 columns]

In [ ]:
# Assuming you have the dataframe df containing student interactions with columns: timestamp, solving_id, question_id, user_answer, elapsed_time, user_id, and is_correct (1 for correct, 0 for incorrect).

# Sort the dataframe by timestamp to ensure the data is in chronological order
merged_df.sort_values(by=['user_id', 'timestamp'], inplace=True)

# Calculate Correctness Rate and Interaction Count for each user
merged_df['correct_count'] = merged_df.groupby('user_id')['is_correct'].cumsum()  # Cumulative sum of correct answers for each user
print(merged_df['correct_count'])

merged_df['interaction_count'] = merged_df.groupby('user_id').cumcount() + 1  # Cumulative count of interactions for each user
print(merged_df['interaction_count'])

merged_df['correctness_rate'] = merged_df['correct_count'] / merged_df['interaction_count']  # Calculate the correctness rate for each interaction

# Calculate average, minimum, and maximum elapsed time for each user
merged_df['average_elapsed_time'] = merged_df.groupby('user_id')['elapsed_time'].transform('mean')
merged_df['min_elapsed_time'] = merged_df.groupby('user_id')['elapsed_time'].transform('min')
merged_df['max_elapsed_time'] = merged_df.groupby('user_id')['elapsed_time'].transform('max')

# Drop unnecessary columns if needed
merged_df.drop(['correct_count', 'interaction_count'], axis=1, inplace=True)

0            0
1            1
2            2
3            2
4            2
            ..
21667466    15
21667467    15
21667468    16
21667469    17
21667470    17
Name: correct_count, Length: 27904657, dtype: int64
0            1
1            2
2            3
3            4
4            5
            ..
21667466    28
21667467    29
21667468    30
21667469    31
21667470    32
Name: interaction_count, Length: 27904657, dtype: int64

In [ ]:
merged_df['next_is_correct'] = merged_df['is_correct'].shift(-1)

In [ ]:
merged_df.dropna(subset=['next_is_correct'], inplace=True)

In [ ]:
features = ['correctness_rate']

In [ ]:
from sklearn.model_selection import train_test_split

X = merged_df[features]
y = merged_df['next_is_correct']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy: {:.2f}".format(accuracy))
print("Precision: {:.2f}".format(precision))
print("Recall: {:.2f}".format(recall))
print("F1-score: {:.2f}".format(f1))

Accuracy: 0.63
Precision: 0.69
Recall: 0.80
F1-score: 0.74

In [ ]:
from sklearn.ensemble import BaggingClassifier
bag = BaggingClassifier(base_estimator=model, n_estimators=50, random_state=42)

# Train the model on the training data
bag.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = bag.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy: {:.2f}".format(accuracy))
print("Precision: {:.2f}".format(precision))
print("Recall: {:.2f}".format(recall))
print("F1-score: {:.2f}".format(f1))

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(